- sampler.go
- sampler_test.go
> Remove redundant field, expose sampling rate from Probabilistic sampler

- Makefile
- context.go
- context_test.go
- crossdock/server/server_test.go
- crossdock/server/trace.go
- propagation.go
- propagation_test.go
- sampler.go
- sampler_test.go
- thrift_span.go
- tracer.go
- tracer_test.go
- transport/zipkin/http_test.go
- zipkin.go
- zipkin/propagation.go
- zipkin/propagation_test.go
- zipkin_test.go
> Replace uint64 trace/spanID with 128bit/64bit strong types

- config/config.go
- config/config_test.go
- config/options.go
- reporter.go
- reporter_options.go
- reporter_test.go
- sampler.go
- sampler_test.go
- transport/zipkin/http_test.go
Refactored the functional options for Config, Reporter, and Sampler. Will do Tracer refactor in separate diff if this PR is fine
> Refactor functional options

- sampler_test.go
The panic was caused when we updated the sampler from adaptive sampler to any other type of sampler.
> Add regression tests around panic

- .travis.yml
- Makefile
- crossdock/Dockerfile
- crossdock/docker-compose.yml
- crossdock/rules.mk
- travis/build-crossdock.sh
- travis/install-crossdock-deps.sh
- Adding endtoend crossdock tests
- Using scratch base docker image to reduce size of the image
- Splitting up the travis job into 2 via matrix to improve build times
> Add endtoend crossdock tests

- jaeger_span.go
- jaeger_span_test.go
- propagation_test.go
- reference.go
- span.go
- tracer.go
- tracer_test.go
This PR converts opentracing.SpanReference to jaeger.SpanRef
Future PRs will rip out zipkin specific stuff ala https://github.com/uber/jaeger-client-java/pull/142
> Build jaeger.SpanRef

- jaeger_span_test.go
- propagation_test.go
- span.go
- thrift_span.go
- thrift_span_test.go
- tracer.go
- tracer_test.go
The other PR (https://github.com/uber/jaeger-client-go/pull/147) was getting too big so broke out this little piece. Will try to get this one to land first and rebase the other PR onto this.
> Move zipkin specific logic into thrift_span.go

- travis/build-crossdock.sh
See: https://github.com/uber/jaeger/pull/153
> Skip upload to docker hub from forked repo PRs

- glide.lock
- glide.yaml
Resolves #177
Related: https://github.com/uber/tchannel-go/pull/634
> Pin thrift < 0.11

- constants.go
- header.go
- header_test.go
- tracer.go
- tracer_options.go
Minor clean-up after #176 
cc @frankgreco
> Support custom tracing headers (clean-up)

- config/config.go
- config/config_test.go
- internal/baggage/remote/options.go
- internal/baggage/remote/restriction_manager.go
- internal/baggage/remote/restriction_manager_test.go
Address cleanup comments from: https://github.com/uber/jaeger-client-go/pull/182
> Clean up baggage restriction manager

- README.md
- config/example_test.go
> Link to real example

- README.md
this seems to work as intended.
> add install instructions. fix #184

- glide.lock
- glide.yaml
Per https://github.com/uber/jaeger-lib/issues/21#issuecomment-324108842
> Use semver of jaeger-lib

- .travis.yml
- CONTRIBUTING.md
Per https://github.com/uber/jaeger/issues/409
> Set import path prior to repository move to jaegertracing org

- .travis.yml
- CONTRIBUTING.md
- DCO
- Makefile
- README.md
- scripts/updateLicense.py
Resolves #208
Signed-off-by: Yuri Shkuro <ys@uber.com>
> Add DCO and update instructions

- .gitignore
- crossdock/Dockerfile
- crossdock/docker-compose.yml
- crossdock/endtoend/handler.go
- crossdock/endtoend/handler_test.go
- crossdock/main.go
- crossdock/rules.mk
- crossdock/server/server.go
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
> Xdock use jaeger compose file

- README.md
Signed-off-by: bin liu <liubin0329@gmail.com>
> fix markdown format error that not correctly render the link

- config/config.go
- config/config_test.go
- transport/zipkin/example_test.go
> Use SetGlobalTracer instead of deprecated InitGlobalTracer

- reporter.go
- reporter_test.go
That causes panics in our service occasionally (during the deployment) when SIGTERM was received, though requests still let through (different problem).
This p/r intended to check whether reporter was already closed prior to attempting to report the span.
> Do not send spans over closed channel in the Reporter

- reporter.go
Part of https://github.com/jaegertracing/jaeger/issues/151
> Change default flush interval to 1sec

- CHANGELOG.md
- constants.go
Signed-off-by: Yuri Shkuro <ys@uber.com>
> Prepare release 2.12.0

- CONTRIBUTING.md
refs https://github.com/jaegertracing/jaeger/issues/771
Signed-off-by: B0go <victorbogo@icloud.com>
> Change "good commit" reference and inline it

- .travis.yml
- Gopkg.lock
- Gopkg.toml
> Test with Go 1.9

- README.md
> Document that JAEGER_SAMPLER_MANAGER_HOST_PORT should be URL

- CHANGELOG.md
- constants.go
Signed-off-by: Won Jun Jang <wjang@uber.com>
> Prepare release 2.15.0

- CHANGELOG.md
- constants.go
Signed-off-by: Won Jun Jang <wjang@uber.com>
> Back to development

- crossdock/rules.mk
Fixing fall out from jaegertracing/jaeger#1229
> Point to tchannel-based docker-compose

- config/options.go
- rpcmetrics/metrics.go
- zipkin/doc.go
Signed-off-by: yeya24 <ben.ye@daocloud.io>
Some typo fix
> fix some typos

- context.go
- header.go
- header_test.go
- propagation.go
- propagation_test.go
- tracer.go
- tracer_options.go
Extracting this bit from #312. I'll add docs if this makes sense.
> Make propagators public to allow wrapping

- Gopkg.lock
- glide.lock
- tracer.go
- tracer_test.go
Use test harness added in https://github.com/opentracing/opentracing-go/pull/146
> Use test harness

- CHANGELOG.md
- constants.go
> Prepare release 2.16

- config/config.go
- config/config_test.go
> Don't complain about blank service name if tracing is Disabled

- CHANGELOG.md
- constants.go
- Prepare for release
- Prepare for release
> Prepare for release 2.17.0

- .travis.yml
- Makefile
To ensure that only glide is used when asked for
> Pass USE_DEP to make

- CHANGELOG.md
- constants.go
Signed-off-by: jung <jung@uber.com>
- NA
- Preparing for release 2.18.0
> Preparing for release 2.18.0

- crossdock/docker-compose.yml
- Adds nodejs to crossdock tests
> Add nodejs to crossdock tests

- sampler.go
- sampler_v2_test.go
- span.go
> Add more tests for delayed sampling

- .travis.yml
- Makefile
- experimental/priority_sampler.go
- experimental/priority_sampler_test.go
- experimental/tag_sampler.go
- experimental/tag_sampler_test.go
- internal/baggage/remote/restriction_manager_test.go
- sampler.go
- sampler_remote_test.go
- sampler_test.go
- sampler_v2.go
- sampler_v2_test.go
- span.go
- span_context.go
> [experimental] Add tag matching and priority samplers

- sampler.go
- sampler_remote.go
- sampler_remote_test.go
- utils/rate_limiter.go
- utils/rate_limiter_test.go
> Stop using Sampler.Equal()

- CHANGELOG.md
- README.md
- constants.go
> Prepare release 2.20

- CHANGELOG.md
- constants.go
- 
- Update CHANGELOG with new tagged release
> Preparing for release 2.21.0

- .travis.yml
> Upgrade build to Go 1.15

- README.md
- tracer_options.go
> Document tracer initialization better
