jaegertracing/jaeger-client-go

.travis.yml, Makefile, crossdock/client/client.go, crossdock/client/client_test.go, crossdock/client/trace.go, crossdock/common/constants.go, crossdock/rules.mk, crossdock/server/server.go, crossdock/server/server_test.go, crossdock/server/tchannel.go, crossdock/server/trace.go, crossdock/thrift/tracetest.thrift, crossdock/thrift/tracetest/ttypes.go
The tchannel service name was incorrectly hardcoded to "go".
This was creating false positives in Java crossdock tests,
since Java client does not yet support TChannel, but the
tests were succeeding because Go service was always called.
=> Pass service name as part of Downstream instruction

context.go, glide.lock, tracer.go, tracer_test.go
When requests were coming from old tchannel, the Zipkin codec would
return `emptyContext, opentracing.ErrSpanContextNotFound`, but that
empty context was then passed to `ChildOf()` and treated as a real
parent reference, resulting in a new trace like `0:6ca9d0ce0d287:0:0`.
=> Check childOf reference for non-empty context before using as parent

glide.lock, glide.yaml, internal/spanlog/json.go, reporter_test.go, span.go, thrift_span.go, thrift_span_test.go, tracer.go, tracer_options.go, tracer_test.go, utils/utils.go
https://github.com/opentracing/opentracing-go/pull/108
TODO:
=> Upgrade to the new K/V Span logging API

glide.lock, glide.yaml
Summary: in
https://github.com/uber/jaeger-client-go/commit/203a3fbf29f54c0729b079fc9f84e25eefc114b2
we pinned github.com/apache/thrift to a specific hash to be consistent
with tchannel-go.  Now that tchannel-go seems to be pinned on master for
apache/thrift we should update jaeger's dependencies as well (also
to avoid transient failures from pinning to a direct version)
=> Unpin Apache Thrift from a direct version, use master instead

CHANGELOG.md, README.md, constants.go, propagation.go, propagation_test.go, tracer.go
Making a request with a `jaeger-baggage` request creates a
root span even without a trace.
See https://github.com/uber/jaeger-client-go/issues/45
=> Add a jaeger-baggage header for easier baggage passing

config/config.go, metrics.go, sampler.go, sampler_test.go, thrift-gen/sampling/ttypes.go
The goal of this diff is to ensure that the adaptive sampler is not recreated every minute and only the samplers that need to be updated are updated.
Followup to this diff will be to remove the Equal() function from Sampler API and add an update() function to each sampler respectively.
=> Add update function to adaptive sampler

crossdock/endtoend/handler.go, sampler.go
Go client is using thrift 0.9.3 so it should use the /sampling endpoint when communicating with the host for integration tests.
There has to be another PR that appends "sampling" to the httpSamplingManager hostport
=> Fix sampling hostport for integration tests.

CHANGELOG.md, README.md, zipkin/README.md, zipkin/doc.go, zipkin/propagation.go, zipkin/propagation_test.go
This PR adds support for Jaeger to handle headers coming from Zipkin tracers.
It can inject, extract:
- 64 bit TraceIds
- 64 bit SpanIds
- 64 bit ParentIds
- Sampled flag
The functionality is basicly copied from my [earlier repo](https://github.com/szdavid92/jaeger-client-go-http-b3-propagation).
=> Support Zipkin HTTP B3 propagation format

README.md
I left a typo and a broken link in the readme file.
=> fix broken link and typo in README

config/config.go, config/config_test.go, crossdock/client/client_test.go, crossdock/endtoend/handler_test.go, crossdock/main.go, glide.lock, log/logger.go, log/logger_test.go, log/zap/logger.go, log/zap/logger_test.go, logger.go, logger_test.go, reporter.go, reporter_options.go, sampler.go, sampler_options.go, sampler_test.go, tracer.go, tracer_options.go, tracer_test.go, transport/zipkin/example_test.go, transport/zipkin/http.go, transport/zipkin/http_test.go
This is a breaking change, we should maybe consider keeping the original log as is and add the zap-log directory, or rererelease 2.0.0 again
=> Add zap logger support

glide.lock, log/zap/logger.go, log/zap/logger_test.go
Addressing the comments from: https://github.com/uber/jaeger-client-go/pull/93
=> Make zap logger more efficient

CHANGELOG.md, config/config.go, config/options.go, observer.go, observer_test.go, span.go, tracer.go, tracer_options.go
Intended to add observer to emit RPC metrics.
@black-adder @badiib
=> Introduce Observer and SpanObserver

log/zap/field.go, log/zap/field_test.go
Since opentracing implementations differ in how they represent tracing data
(e.g., not all implementation use span and trace IDs), there isn't a generic way
to add tracing information to log messages. This PR adds a small utility to
Jaeger's zap integration that extracts structured data from a context.Context.
This is an exact clone of the code currently in UberFX's `ulog` package; for
easy re-usability, I think that this is a better place for it. I'm happy to
remove the code in UberFX once this lands.
=> Add a structured way to extract traces for logging

observer_test.go, propagation_test.go, reporter.go, reporter_test.go, span.go, span_test.go, thrift_span.go, thrift_span_test.go, tracer.go, tracer_test.go, zipkin_test.go
For example, allow access to span.OperationName(), introduced in the same PR
=> Make Span type public to allow access to non-std methods for testing

rpcmetrics/metrics.go, rpcmetrics/metrics_test.go, rpcmetrics/observer.go, rpcmetrics/observer_test.go
In practice, the precision of the recorded timing values
depends on the metrics backend and the client library.
Since we're using time.Duration based API, we cannot claim
the unit of measure in the metric name.
* Success/failure are distinguished by `error=true|false` tag.
* HTTP Requests are distinguished by `status_code=2xx|3xx|...` tag
=> Rename RPC metrics and use more tags

sampler.go, sampler_test.go
Fixes #69 
A panic might occur when multiple threads try to create a new sampler in AdaptiveSampler.IsSampled()
=> Add mutex to adaptiveSampler

CHANGELOG.md, config/config.go, config/config_test.go, config/options.go, config/options_test.go
Also renames config ClientOptions to Options and adds `applyOptions()` func to match Jaeger backend coding patterns.
=> Add config option to initialize RPC Metrics feature

sampler_test.go, utils/rate_limiter.go, utils/rate_limiter_test.go
This ensures that GuaranteedThroughputProbabilisticSampler will always sample a new operation the first time it sees it.
=> Initialize rate limiter balance with maxBalance

config/config.go, config/config_test.go, rpcmetrics/metrics.go, rpcmetrics/metrics_test.go, rpcmetrics/normalizer.go, rpcmetrics/observer.go, rpcmetrics/observer_test.go, rpcmetrics/operations.go, rpcmetrics/operations_test.go
Part 1 of https://github.com/uber/jaeger-client-java/issues/172
After this, I'll work on abstracting out the metrics to not be http specific
=> Rename endpoint to operation for RPC metrics

jaeger_span_test.go, propagation_test.go, span.go, span_test.go, testutils/mock_agent_test.go, thrift_span_test.go, tracer.go
We want to save the baggage when it is first set within the span. I think it makes sense to make baggage a first class item.
The new [jaeger.thrift idl](https://github.com/uber/jaeger-idl/blob/master/thrift/jaeger.thrift) will look like:
```
struct BaggageRecord {
1: required string key
2: required string value
3: optional i64 timestamp
}
struct Span {
...
12: optional list<BaggageRecord> baggageRecords
}
```
Alternatives would be either tags or logs.
tag: we only have key-value so it would have to be a json blob of baggage:{key, value, timestamp}
log: same as above, we would have to use the fields which are key-value as well (json blob)
By making this a first class citizen, we don't need to manually parse the tags/logs for the UI.
Why timestamp in BaggageRecord? If the same baggage key …
=> Save baggage in span

CHANGELOG.md, reporter.go
=> Move queueLength to the top of the struct to guarantee 64bit alignment

jaeger_thrift_span.go, transport/http.go, transport/http_test.go, transport_udp.go
=> Support HTTP transport with jaeger.thrift

config/config.go, config/config_test.go, rpcmetrics/endpoints.go, rpcmetrics/endpoints_test.go, rpcmetrics/metrics.go, rpcmetrics/metrics_test.go, rpcmetrics/normalizer.go, rpcmetrics/observer.go, rpcmetrics/observer_test.go
This reverts commit c762689dafff561d710e838bd2aef537f90294a2.
This is a breaking change and will be removed for 2.7.0
=> Revert "Rename endpoint to operation for RPC metrics (#150)"

testutils/mock_agent.go
These test utility functions were removed before, adding them back to not break* the API.
*break is subjective here
=> Add deprecated mock agent functions

CHANGELOG.md, constants.go, jaeger_thrift_span_test.go
It was only needed in Zipkin format to label the tag as process-level.
=> Drop `jaeger.` prefix from `jaeger.hostname` process-level tag

CHANGELOG.md, CONTRIBUTING.md, RELEASE.md, constants.go
- Pin thrift <= 0.10 (#179)
- Introduce a parallel interface ContribObserver (#159)
=> Release 2.9.0

config/config.go, config/config_test.go, config/options.go, config/options_test.go, tracer_options.go, tracer_test.go
Signed-off-by: Jingwen Peng <pengsrc@icloud.com>
=> Add option to enable gen128Bit for tracer

sampler.go
I noticed this when writing C++ implementation. `adaptiveSampler` seems to skip closing its `defaultSampler`. For the current code, it doesn't matter, since all `Close` functions/methods are left unimplemented. But thought I'd submit this anyway.
=> Close defaultSampler field in adaptiveSampler.

propagation_test.go, span.go, span_test.go
It is not done in the clients in other languages, and is not necessary until the keys go into http headers. At the moment we already convert to lower case when extracting the keys from text map
```
key := strings.ToLower(rawKey) // TODO not necessary for plain TextMap
```
=> Do not coerce baggage keys to lower case

reporter.go
we were getting "span is too large" errors, but without having any indication of which span, it's hard to guess why it might get too large.
logging the operationname is not super conclusive either, but at least it can be a good hint.
=> when a span can't be reported, log its name

tracer.go, tracer_options.go, tracer_test.go
Allow high 64 bits of trace ID to be set to the first 64 bits of SHA256 of service name. This is a quick way to identify the originator of a given trace.
=> Add option for consistent high trace ID

scripts/updateLicense.py
Signed-off-by: Won Jun Jang <wjang@uber.com>
See https://github.com/jaegertracing/jaeger/commit/d7d1c74fa74f77d2c7faa50a0c568f979d9a30fd
I think we have too many repos... would it make sense to have this script in one place and have all the repos reference it?
=> Avoid rewriting copyright year in the license header

log/logger.go, log/logger_test.go, reporter.go, reporter_test.go, sampler_test.go
Fix #244 by using a single queue. The channel remains open after the reporter is closed, but the worker go-routine is stopped with guaranteed flushing of all spans reported before Close() is called.
Alternative to #239 and #241
=> Fix race condition between Report and Close methods

config/config.go, config/config_test.go, config/options.go, config/options_test.go
Re: https://github.com/jaegertracing/jaeger-client-go/issues/262
This PR adds the ability to specify custom Injectors and Extractors when creating new Tracers using the Configuration struct.
Usage:
```go
c := jaegerconfig.Configuration{}
tracer, closer, err := c.New(
"service",
jaegerconfig.Injector("custom.format", CustomInjector{}),
jaegerconfig.Extractor("custom.format", CustomExtractor{}),
)
```
=> Add Configuration support for custom Injector and Extractor

glide.yaml
I've been having a lot of trouble with glide on a new service I'm developing. One error message involved conflicting dependencies of testify, and I think jaeger-client-go may be the cause. Either way, this seems like a good change.
Signed-off-by: Keith Lea <keithl@uber.com>
=> Move testify dependency to testImport

span.go, span_test.go
Resolves #267
Signed-off-by: Yuri Shkuro <ys@uber.com>
=> Use lock when retrieving span.Context()

README.md, config/config.go, config/config_env.go, config/config_test.go, config/example_test.go, constants.go, transport_udp.go
Status: I'm opening this PR mostly to get an early feedback on the general direction. I have the feeling that my Java background might be getting in the way, so, I wanted to catch any fundamental problem early on :)
As it is, this PR implements the configuration of the following properties, like from the Java Client:
Additionally, these are the properties that are unique to the Go client:
The following properties will not be implemented, as the underlying feature is not available for the Go client:
The following property will not be implemented, as the underlying feature behaves differently in the Go client than in the Java client:
Closes #206 
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
=> Add support for client configuration via env vars

sampler.go, sampler_test.go
Fixes #259 
Signed-off-by: Scott Kidder <scott@mux.com>
=> Fix the RemotelyControlledSampler so that it terminates go-routine on Close()

README.md, config/config.go, config/example_test.go
The new function is defined on a pointer received, making it harder to use, e.g. below doesn't work even when using the `&`:
```go
tracer, closer, err := &jaeger.Configuration{
ServiceName: *name,
Sampler:     &jaeger.SamplerConfig{Type: "const", Param: 1},
}.NewTracer()
```
Also correct the naming of examples functions to match godoc guidelines, and fix README examples.
=> Use value receiver for config.NewTracer()

crossdock/docker-compose.yml
=> Remove tchannel tests from crossdock

internal/throttler/remote/throttler_test.go
Signed-off-by: Isaac Hier <ihier@uber.com>
#299 
- Avoid use of `time.Sleep` and call function directly.
=> Fix throttler test by avoiding time.Sleep

Makefile, scripts/updateLicenses.sh, thrift-gen/agent/agent.go, thrift-gen/agent/constants.go, thrift-gen/agent/ttypes.go
=> Fix bad imports caused by splitting IDL files

Gopkg.lock, glide.lock, glide.yaml, tracer.go
Signed-off-by: Isaac Hier <ihier@uber.com>
- Resolves #292.
- Remove UUID library in favor of 64 bit random numbers. Only needed to distinguish multiple clients acting on behalf of the same service communicating with a single agent. Even in the unlikely case of collision, the only outcome would be that debug spans might be disabled for clients longer than they should be, but nothing major.
=> Get rid of satori/go.uuid library

zipkin/README.md
Signed-off-by: liukgg <liuk1991@sina.com>
Add an example to show how to use NewZipkinB3HTTPHeaderPropagator() while following the guides from official godoc(https://godoc.org/github.com/uber/jaeger-client-go/config#example-Configuration-InitGlobalTracer-Production). It's because I could not get straight guides when I tried to use jaeger with istio which uses the Zipkin B3 HTTP Header to propogate tracing data.
Add a new example  to show how to use NewZipkinB3HTTPHeaderPropagator()  in the README.md file.
=> Add an example for Zipkin B3 Propagator

propagation_test.go, tracer.go
This PR fixes the `StartSpan()` logic so that spans started with a `FollowsFrom` reference to a dummy parent (i.e., a parent used for carrying baggage items or debug ID extracted from HTTP headers) are set with the correct baggage items or debug ID, respectively.
Previously, these headers were in effect only if the span was started with a `ChildOf` reference to the dummy header.
The condition used in `StartSpan()` to determine whether the `parent` variable holds a valid span context reference was extended to check if there's a debug ID / baggage items present.
The existing unit tests for baggage items / debug ID headers were also extended to repeat the test for both `ChildOf` and `FollowsFrom` reference types.
Signed-off-by: Zvi Cahana <zvic@il.ibm.com>
=> Fix FollowsFrom spans ignoring baggage/debug header from dummy parent context

config/config.go, config/options.go, config/options_test.go, constants.go, jaeger_thrift_span.go, jaeger_thrift_span_test.go, span.go, tracer.go, tracer_options.go, zipkin_thrift_span.go, zipkin_thrift_span_test.go
Fix #314 #232
Related to #316 
Instead of removing the truncated string and max annotation length, make the max annotation length configurable in tracer options for backward compatibility. Maybe we can also support no limit for max annotation length. but that is open for discussion.
Signed-off-by: Eric Chang <chiahan1123@gmail.com>
=> Make maximum annotation length configurable in tracer options

README.md, config/config.go, config/config_env.go, config/config_test.go
- https://github.com/jaegertracing/jaeger/issues/920
- Previously, the client could only send spans via UDP to the agent.
This PR adds support for sending spans using HTTP to the collector
by setting the JAEGER_ENDPOINT env var. Additionally, the HTTP
transport can be secured through basic auth by setting the
JAEGER_USER and JAEGER_PASSWORD env vars.
Signed-off-by: Daneyon Hansen <danehans@cisco.com>
=> Support more environment variables in configuration 

sampler.go, sampler_test.go
=> Print error on Sampler Query failure

transport/http.go, transport/http_test.go, transport/zipkin/http.go, transport/zipkin/http_test.go
Adds an HTTPOption to the HTTP exporters that allows overriding the
underlying http.RoundTripper to use on the *http.Client. This is useful
for designs that require more flexibility than just a URL, for instance
when forwarding spans to a local Envoy proxy over a unix domain socket.
- This PR allows overriding the `http.RoundTripper` on the HTTP exporters' underlying `*http.Client`s. This is useful for use cases like forwarding span data to a unix domain socket.
- Adds an `HTTPOption` for setting `http.RoundTripper` on the various HTTP exporters
=> collector http transport: support custom http.RoundTripper (#332)

transport/zipkin/http.go, transport/zipkin/http_test.go
Signed-off-by: Michael Puncel <mpuncel@squareup.com>
- The zipkin HTTP transport silently swallows HTTP errors, for instance when the URL path is misconfigured and getting 404s when flushing spans
- Return an error if the HTTP response code is >= 400 (which is what the normal jaeger transport does)
- Read entire response body and close it to ensure connections don't leak
=> zipkin transport: return error when an HTTP error code is seen (#330)

Makefile
- Fix build break
```
package github.com/golang/lint/golint: code in directory /home/travis/gopath/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
make: *** [install-ci] Error 1
```
- https://github.com/golang/lint/issues/415#issuecomment-429050481
- https://travis-ci.org/eundoosong/jaeger-client-go/builds/445113715?utm_source=github_status&utm_medium=notification
=> Fix golint import path

.travis.yml, config/config_test.go, crossdock/endtoend/handler.go, transport/zipkin/http_test.go
Signed-off-by: Eundoo Song <eundoo.song@gmail.com>
- Upgrade go version to 1.11.1
- Upgrade go version to 1.11.1
- Fix gofmt error caused from 1.11.1
```
go fmt or license check failures, run 'make fmt'
./crossdock/endtoend/handler.go
./transport/zipkin/http_test.go
./config/config_test.go
make[1]: *** [lint] Error 1
make: *** [test-ci] Error 2
```
=> Upgrade go version to 1.11.1

tracer.go
when creating span ids
Signed-off-by: Gary Brown <gary@brownuk.com>
Resolves #353 - possibly :)
Instead of using a lock around the random number generation, a pool of `rand.Source`s is maintained.
=> Use a pool of rand.Source to reduce lock contention 

tracer.go
Signed-off-by: Gary Brown <gary@brownuk.com>
Remove `defer` used in generating random number, as recommended by @mandarjog here: https://github.com/jaegertracing/jaeger-client-go/commit/a9d03b8e10febae4d48d348612750db7e74517f8#r31655784
Instead of putting generator back in pool using defer, do it explicitly.
=> Avoid defer when generating random number

.travis.yml, Makefile
Changes travis config to run another matrix step with Go N-1 version, but exclude running lint/fmt because those are likely to break betwen versions.
=> Resolves #344: Run tests with N-1 version of Go

baggage_setter_test.go, config/config_test.go, internal/baggage/remote/restriction_manager_test.go, internal/throttler/remote/throttler_test.go, metrics.go, metrics_test.go, propagation_test.go, reporter_test.go, rpcmetrics/observer_test.go, sampler_test.go, tracer_test.go
Normalisation of the metric names used across the Jaeger tracers implemented in different languages as discussed in jaegertracing/jaeger#572.
As discussed [here](https://github.com/jaegertracing/jaeger/issues/572#issuecomment-426980837), the Go client metric names have been changed so that the `jaeger_client_jaeger_<metricName>` format (reported by Go client in jaeger-query) can now be controlled by the application - and therefore a convention such as `jaeger_tracer_<metricName>` can be adopted.
The other part of the change relates to the `_total` suffix on counter metrics reported to Prometheus. This fix has been applied to `jaeger-lib` and a snapshot version is currently referenced in the `glide.lock` file.
QUESTION: Should this PR wait for a released version of `jaeger-lib` before …
=> Change metrics prefix to jaeger_tracer and add descriptions

.travis.yml, Gopkg.lock, Makefile
This PR does the following
i) updates go-1.11.1 to go-1.11.5 and go-1.10.5 to go-1.10.8 . Reason: There have been multiple patch release fixes across these patch releases.
ii) updates dep 0.3.2 to dep 0.5.0. Reason: There have been multiple performance and accuracy improvements in dep's dependency resolution since 0.3.2.
=> use latest releases of golang and dep in jaeger-client-go

zipkin/propagation.go, zipkin/propagation_test.go
Signed-off-by: Douglas Reid <douglas-reid@users.noreply.github.com>
- Zipkin propagation logic does not support 128bit trace IDs
- Use existing TraceID support for 128bit parsing/serialization instead of custom logic in the propagation.go file
=> Update zipkin propagation logic to support 128bit traceIDs

thrift-gen/jaeger/ttypes.go, thrift-gen/zipkincore/constants.go, thrift-gen/zipkincore/ttypes.go, zipkin_thrift_span.go, zipkin_thrift_span_test.go
Includes:
- Updating IDL to `3471ffb`
- Running make thrift
- Add TraceIDHigh to zipkin_thrift_span
Note: I manually verified this by running a binary with these changes compiled in, as illustrated in https://github.com/istio/istio/issues/11954#issuecomment-466594923.
Signed-off-by: Douglas Reid <dougreid@google.com>
- Zipkin trace export drops the high order 64bits from trace ids
- updated the idl submodule, ran the thrift-gen, added a few lines to include the new field.
=> Add support for 128bit trace ids to zipkin thrift spans.

Gopkg.lock, Gopkg.toml, Makefile
Signed-off-by: Prithvi Raj <p.r@uber.com>
- Gopkg.yaml can get out of sync with Gopkg.lock
- Run `dep check` and fail build if they diverge
- Reorder dependencies in gopkg.yaml so that they are in the same order as glide.yaml
=> Verify dep files (Gopkg.yaml/Gopkg.lock) are in sync

config/config.go, config/options.go, config/options_test.go
- lack of support for enabling pooling of spans from config object
- add Config setter for PoolSpans and pipe it through to Tracer construction
=> Allow setting of PoolSpans from Config object

zipkin/propagation.go, zipkin/propagation_test.go
Related to https://github.com/jaegertracing/jaeger/issues/755#issuecomment-393929718
=> Add baggage to B3 codec

span.go, span_test.go
Fixes #394
While Jaeger supports user-supplied reporters span data is not exported to external packages. Custom reporters should have the ability to access span data.
=> Expose span data to custom reporters [fixes #394]

tracer.go, tracer_test.go
old codes did not support passing a iptag to NewTracer because NewTracer
will overwrite the iptag. Now modify the NewTracer method, make it
support passing iptag
two private method of Tracer add : getTag, setTag
And testing function is also added into tracer_test.go, all test of
NewTracer passed.
Signed-off-by: Canliu Wu <kvcsgame@hotmail.com>
Resolves #401 
- 
modified the part of setting iptag in NewTracer method so that NewTracer won't overwrite the iptag the user pass in. Two necessary private method added : setTag, getTag
and test codes also added in tracer_test.go : line 340-371
all tests of NewTracer passed
=> NewTracer suport passing iptag [fixes #401]

README.md, constants.go, span.go, tracer.go, tracer_test.go
refs #397
- This allows client to initialize a span from an already identified ("offline") context.  
- Introduces a Jaeger specific span reference type `"self"`
- Allows client to pass in an already established `SpanContext`, if so, will use the passed in `SpanContext` for the span instead of generating span/trace ids
---
=> Self Referenced Span

sampler.go, sampler_test.go
Fixes #412 
- On update, collect samplers explicitly requested in the config, and discard all others.
This fixes the problem I encountered, and also the issue that if you remove an entry from strategies, the sampler persists.
- Add unit test covering both types of update. I apologise the test code seems clumsy, maybe I don't understand the framework well.
Downside of this change is that default-rate samplers are discarded even when the default rate doesn't change, so the rate-limiting part will start from scratch. Doing this better seems to require much more extensive changes to remember how things were set up.
=> Update default rate

config/config_env.go, config/config_test.go, constants.go
Resolves #388 
If `JAEGER_AGENT_HOST` is set but `JAEGER_SAMPLER_MANAGER_HOST_PORT` is not, default the sampler manager to point at the agent.
=> Default sampling server URL to agent

constants.go, sampler.go
To avoid duplicating the port number
=> Combine constants and reuse port

context.go, context_test.go, span.go, span_test.go
Add `0b100` as a constant for Firehose mode and allow setting and checking
this on the span context.
fixes #417
ref https://github.com/jaegertracing/jaeger/issues/1731
Signed-off-by: Prithvi Raj <p.r@uber.com>
=> Add a flag for firehose mode

config/config.go, config/config_test.go, config/options.go, config/options_test.go, span.go, span_test.go, tracer.go, tracer_options.go, tracer_test.go
- Resolves #422 
- Add "sampleWithoutDebugFlag" option when initialize tracer
- Update setSamplingPriority logic to set debug flag accordingly
- Avoid race condition update set firehose flag
=> Add "sampleWithoutDebugFlag" option for tracer to decide set/not set debug flag when a span is forced to be sampled

.travis.yml, CONTRIBUTING.md, Makefile, README.md
According to https://github.com/jaegertracing/jaeger-lib/pull/75#issuecomment-528639764, enabling go modules is more complicated when the library is on a version above 1.x, which is the case with jaeger-client-go and jaeger-lib.
For now, removing go modules. Will revisit in the future along with potential renaming of the path from /uber/ to /jaegertracing/
Reopens ##382
=> Remove go modules

Gopkg.lock, Gopkg.toml, Makefile, glide.lock, glide.yaml
Resolves #433 
Currently uses private branch of jaeger-lib, pending jaeger-lib 2.2 release
TODO:
=> Upgrade jaeger-lib to 2.2 and unpin Prom client

config/config_env.go, config/config_test.go
- allow the user to override that configuration via env vars
- Added another method with config receiver and modified the existing method to call the method with config receiver.
Signed-off-by: vineeth <vineeth.pothulapati@aquasec.com>
Resolves: #430
=> Allow config.FromEnv() to enrich an existing config object

log/zap/field.go, log/zap/field_test.go
When a trace is logged, we don't report whether it was sampled, so users
don't know whether they can look it up in the system.
This changes log/zap to log this information.
Resolves #444
=> log/zap: Report whether a trace was sampled

sampler.go, sampler_remote.go, sampler_remote_options.go, sampler_remote_test.go, sampler_test.go, sampler_v2_test.go, span.go
=> Upgrade all samplers to v2

experimental/sampler_custom_updater_test.go, experimental/tag_sampler.go, sampler_remote.go, sampler_remote_options.go, sampler_remote_test.go, testutils/mock_agent.go, testutils/sampling_manager.go
Part of #449, to allow parsing custom/extended strategy response from the agent
- delegate updating individual samplers to replaceable SamplerUpdater(s)
- introduce replaceable sampling strategy Fetcher and Parser
- add unit tests simulating custom sampler
=> Refactor remote sampler for better extensibility

propagation_test.go, sampler.go, sampler_test.go, span_context.go, tracer.go
* Similar to https://github.com/jaegertracing/jaeger-client-node/pull/410
* Part of #449 
Per-operation adaptive sampling should only apply to service endpoints, not to operation names of the inner/children spans. Otherwise it's a problem for adaptive sampling backend that only records operations from the root spans, meaning all child operations are getting the default probability, which may be higher than the calculated probabilities.
- Add a test that demonstrates the problem.
- Change per-operation sampler to only allow sampling "local root spans", which is equivalent to the actual root span of the trace because spans with remote parent are finalized right away.
=> Do not apply adaptive sampler to child spans

crossdock/client/client_test.go, sampler.go, sampler_remote.go, sampler_remote_test.go, sampler_test.go, sampler_v2_test.go, scripts/bench.Makefile, tracer_bench_test.go
Part of #449.
Recent changes to `adaptiveSampler` introduced a potential performance degradation, addressed here via a new opt-in option `OperationNameLateBinding`:
> Opt-in feature for applications that require late binding of span name via explicit call to `SetOperationName`. When this feature is enabled, the sampler will return `retryable=true` from `OnCreateSpan()`, thus leaving the sampling decision as non-final (and the span as writeable). This may lead to degraded performance in applications that always provide the correct span name on trace creation.
The PR also renames `AdaptiveSampler` to `PerOperationSampler`, to better reflect its purpose. The public name AdaptiveSampler has not been released yet, the previous release had it private `adaptiveSampler`.
Legend:
* …
=> Make delayed sampling optional

config/config.go, config/config_test.go, experimental/sampler_custom_updater_test.go, sampler_remote.go, sampler_remote_test.go, tracer.go, tracer_test.go
When testing custom configuration mechanism, which in turn uses `config.Configuration` type here, it is not possible to assert what kind of sampler is created, aside from very convoluted way of observing that via side effects.
- Add Sampler() function to the Tracer.
- Rename GetSampler() to Sampler() on the remote sampler, to match the name (non-breaking as the previous name has not been released yet)
- Add Options field to SamplerConfig
=> Expose Sampler on Tracer and accept sampler options via Configuration

span_context.go, x/doc.go, x/priority_sampler.go, x/priority_sampler_test.go, x/sampler_custom_updater_test.go, x/tag_sampler.go, x/tag_sampler_test.go
To follow Go conventions.
Part of #449
=> Rename package experimental to x

Gopkg.lock, Gopkg.toml, internal/baggage/remote/restriction_manager_test.go
Resolves #463. The correct name is go.uber.org/atomic
NB: I wasn't able to fix glide files, it failed with
```
[INFO]	--> Fetching honnef.co/go/tools.
[UBER]  Gitolite GitHub mirror gitolite@code.uber.internal:github/dominikh/go-tools already exists
[UBER]  Rewrite github.com https://github.com/dominikh/go-tools to gitolite@code.uber.internal:github/dominikh/go-tools
[ERROR]	Error scanning github.com/cespare/xxhash/v2: cannot find package "." in:
/Users/ys/.glide-uber/cache/src/https-github.com-cespare-xxhash/v2
[INFO]	--> Fetching updates for github.com/matttproud/golang_protobuf_extensions.
[INFO]	--> Fetching golang.org/x/tools.
[UBER]  Rewrite golang.org https://golang.org/x/tools to gitolite@code.uber.internal:googlesource/tools
[INFO]	--> Fetching github.com/BurntSushi/toml.
[UBER] …
```
=> Fix github.com/uber-go/atomic import

config/config.go, config/config_test.go, sampler.go, sampler_remote.go, sampler_remote_options.go, sampler_remote_test.go, sampler_test.go
- Make AdaptiveSamplerUpdater usable with default values; Resolves #467
- Create `OperationNameLateBinding` sampler option and config option
- Make `SamplerOptions` var of public type, so that its functions are discoverable via godoc
=> Make OperationNameLateBinding externally configurable

reporter.go, reporter_test.go, transport/zipkin/http_test.go
Tweak log messages to make it obvious they are coming from Jaeger
=> Clarify reporting error logs

crossdock/client/trace.go, crossdock/client/trace_test.go, propagation_test.go, span_context.go, span_context_test.go
=> Do not strip leading zeros from trace IDs

README.md, thrift-gen/zipkincore/ttypes.go
Signed-off-by: Marc Bramaud <m.duboucheron@gmail.com>
- ~3~ 1 typos in `README.md` ~and `thrift-gen/zipkincore/ttypes.go`~
=> chore(docs): fixed a couple of typos

config/config.go, config/config_test.go, transport/http.go, transport/http_test.go
Resolves: #478
When services, such as jaeger-collector, are deployed to production, they are assigned ephemeral IP addresses and ports when listening for HTTP requests.
In order for caller services (whether calling from development or production) to reach specific endpoints of callee services, a side-car process is used to route the outbound request to the correct IP and port which is achieved by providing the:
- caller service name
- target service name
- target HTTP endpoint
Currently, jaeger-client-go does not provide a capability for clients to flexibly add headers to the outbound HTTP request.
- Add a key-value map `Headers` to `ReporterConfig`
- This allows clients to configure custom headers which will be passed to the `NewHTTPTransport`
- These custom headers will be set in the …
=> Provide ability for clients to add HTTP headers

span.go, span_test.go, tracer.go, tracer_options.go
The MaxLogsPerSpan option limits the number of logs in a Span. Events are
dropped as necessary; a log in the finished span indicates how many were
dropped.
Resolves #46
Almost copy of https://github.com/opentracing/basictracer-go/pull/39/commits/723bb40d4f3bf4fcc8d01a1805bde4bd19430502
=> Add limit on log records per span

Makefile, internal/reporterstats/stats.go, internal/transport/stats.go, jaeger_thrift_span.go, reporter.go, thrift-gen/jaeger/ttypes.go, thrift-gen/zipkincore/ttypes.go, transport_udp.go, transport_udp_test.go, utils/udp_client.go, zipkin_thrift_span.go
- https://github.com/jaegertracing/jaeger/issues/2005
- introduce stats reporting in the Batch
=> Report data loss stats to Jaeger backend

transport_udp.go, transport_udp_test.go
- Resolves #486
- Increase batch overhead constant to 70 to account for extra space occupied by data loss metrics
=> Increase UDP batch overhead to account for data loss metrics

sampler.go, sampler_test.go
This commit fixes interconnection of ProbabilisticSampler.IsSampled and tracerOptions.RandomNumber:
- RandomNumber accepts `func() uint64` and doesn't documents it should return 63bit integer
- IsSampled performed check as if random number were 63bit integer.
This fix (suggested by Yuri Shkuro) truncates highest bit before comparison in IsSampled,
therefore it doesn't matter if random number is 63bit or 64bit.
fixes #489 
Signed-off-by: Sokolov Yura <funny.falcon@gmail.com>
=> Unset highest bit of traceID in probabilistic sampler

README.md
Signed-off-by: Febrian Setianto <febrian.setianto@gmail.com>
- Fix 1 typo in `README.md`
- Change `defer closer.Closer()` to `defer closer.Close()`
=> Fix Closer() Typo

Gopkg.lock, log/logger.go, log/logger_test.go, log/zap/logger.go, log/zap/logger_test.go, reporter_options.go, sampler_remote.go, sampler_remote_options.go, sampler_remote_test.go, tracer.go, tracer_options.go
Relates to #501
- Add a debug log interface so that the client may log more details when the supplied logger supports `debug` logging and is configured to log `debug` logs. 
- Add a debug log adapter that converts a standard logger to a debug logger if it satisfies the new interface. If it doesn't, debug logging is disabled.
=> Add a debug logging interface

reporter.go, reporter_test.go, sampler.go, sampler_remote.go, sampler_test.go, tracer.go
Part of #501
- Log tracer and reporter closes
- Log samplers on updates to sampling strategies. By default, these happen once a minute
Signed-off-by: Prithvi Raj <p.r@uber.com>
=> Add debug logs

log/logger.go, log/logger_test.go
- Jaeger components may be initialized with `nil` loggers. 
- Verify that the logger is non-nil before logging in the `DebugLoggingAdaptor` to preserve old behavior
Signed-off-by: Prithvi Raj <p.r@uber.com>
=> Fix regression by handling nil logger correctly

README.md, config/config.go, config/config_env.go, config/config_test.go, constants.go
- Implements jaegertracing/jaeger#1849 for golang client
=> Converge on JAEGER_SAMPLING_ENDPOINT env variable

README.md
- Resolves #484 
- Changes the JAEGER_TAGS description to not allow whitespace (resolves #377)
=> Show default values for env vars

config/config_env.go, config/config_test.go
- Resolves #473 
- Supersedes / Closes #474 
- In `ReporterConfig.reporterConfigFromEnv()`, override reporter agent config only when agent host or port was set in env.
=> override reporter config only when agent host or port was set in env

sampler_remote.go, sampler_remote_test.go, sampler_test.go
Serialize read access for RemotelyControlledSampler.sampler field
Signed-off-by: Dima Kozlov <hummerd@mail.ru>
Serialize access to RemotelyControlledSampler.sampler
Wrap sampler with atomic.Value.
=> Add RLock for RemotelyControlledSampler.sampler Resolves #514

span_context.go, tracer.go, tracer_test.go
- when sending requests with `jaeger-debug-id` header, the root span gets an invalid parent reference resulting in a warning
- do not add span context to references if it does not contain valid trace ID
- fix null pointer error in `SpanContext.String()`
=> Do not add invalid context to references

Gopkg.lock, Gopkg.toml, glide.lock, glide.yaml, jaeger_thrift_span_test.go, zipkin_thrift_span_test.go
* Resolves #524 
* Upgrades opentracing-go dependency to 1.2 (https://github.com/opentracing/opentracing-go/releases/tag/v1.2.0)
* Pin some Prometheus client libs in glide.yaml because some of their dependencies moved to go modules with v2, which is not supported by glide.
=> Upgrade to OpenTracing Go 1.2

span_context.go, span_context_test.go, zipkin/propagation_test.go
The wire encoding of the TraceID uses zero prefixes (#472).
The JaegerUI also uses zero prefixes (since 1.16).
So it makes sense that the Stringer of the TraceID also does this.
Resolves #532
Signed-off-by: Lukas Vogel <vogel@anapaya.net>
=> TraceID.String prefix with zeroes

Gopkg.lock, Gopkg.toml, glide.lock, glide.yaml
=> Upgrade to jaeger-lib@2.3.0 to fix broken codahale/hdrhistogram dependency

sampler_remote.go, sampler_remote_test.go
We've detected some race condition. In case you are using `RemotelyControlledSampler` it will call to Update method for sampler in it's background settings-polling routine. In the same time IsSampled (or any other exposed method of sampler) can be called from another goroutine and try to access sampler's data.
```
2020-10-06_09:52:19.35460 ==================
2020-10-06_09:52:19.35462 WARNING: DATA RACE
2020-10-06_09:52:19.35462 Write at 0x00c000073150 by goroutine 14:
2020-10-06_09:52:19.35463   github.com/uber/jaeger-client-go.(*ProbabilisticSampler).init()
2020-10-06_09:52:19.35463       /project/build/vendor/github.com/uber/jaeger-client-go/sampler.go:130 +0xe4
2020-10-06_09:52:19.35463   github.com/uber/jaeger-client-go.(*ProbabilisticSampler).Update()
2020-10-06_09:52:19.35463 …
```
=> Lock RemotelyControlledSampler.sampler on callbacks

sampler_v2_test.go, span.go, span_context.go, span_test.go, tracer.go
- Fixes #526 
- Made `isWriteable()` and `isSamplingFinalized()` methods on SpanContext
- Changed `setTagInternal()` and `applySamplingDecision()` to retrieve the context appropriately under lock or not
- Changed `setSamplingPriority()` to take a `*samplingState` and other required params
- Reenabled and extended `TestSpanContextRaces()`
**branch**
```
goos: linux
goarch: amd64
pkg: github.com/uber/jaeger-client-go
BenchmarkTracer/sampler=NeverSample/remoteSampler=false/children=false/tags=5/ops=10/cpus-8         	 4943131	       245 ns/op
BenchmarkTracer/sampler=NeverSample/remoteSampler=false/children=true/tags=5/ops=10/cpus-8          	 3944086	       348 ns/op
BenchmarkTracer/sampler=AlwaysSample/remoteSampler=false/children=false/tags=5/ops=10/cpus-8        	 3023574	       400 ns/op …
```
=> Additional context protections

.github/actions/setup-gopath/action.yml, .github/workflows/crossdoc-integration-test.yml, .github/workflows/fossa.yml, .github/workflows/unit-tests.yml
* Add local `setup-gopath` github action and reuse it in other workflows
* it writes to `$GITHUB_ENV` file to expose new env vars to subsequent steps
* it creates a symlink `$GOPATH/src/github.com/uber/jaeger-client-go` and exports it as `$PROJECT` var
* other workflows run this action and the only need to do `cd $PROJECT` before running Go commands
* fixed the GOPATH issue for #551, but FOSSA fails for other reasons now
=> Simplify GOPATH settings in GH actions

config/config.go, config/config_test.go, config/options.go
- I want set tracer randomNumber when the config.New() called
- Added the WithRandomNumber function and the randomNumber field for config.Options. Finally, apply the setting in the config.NewTracer() function
=> feat: extend configuration to support custom randomNumber func

propagation.go, propagation_test.go
Signed-off-by: lastchiliarch <lastchiliarch@gmail.com>
- Trim  baggage key in parseCommaSeparatedMap，see  #271 
-  Trim baggage key when parseing
=> Trim baggage key when parsing

span_context.go, span_context_test.go
- delete a baggage item in span if provided empty value.
- if sets to blank values in span context, then delete a baggage item.
=> Delete a baggage item when value is blank

propagation.go, propagation_test.go
Protect against data corruption between binary Inject and Extract.
E.g. somebody passed in base64 data without remembering to decode it...
Assume the data is corrupt and return an error instead of attempting to allocate hundreds of megabytes.
The test I have added still fails without the new checks, but takes about 6 seconds longer because `make(map[string]string, 1094795585)` is quite slow and requires 5GB of RAM.
=> Check for unreasonable data in binary propagation

CHANGELOG.md
- Fixes #572 
- Update changelog
=> Preparing for release 2.26.0

constants.go
- Correct JaegerClientVersion in constants.go for 2.26.0
=> Release 2.26.0 - Update JaegerClientVersion

config/config.go
- Resolves #570
- HTTP transport batch size no longer overridden from default 100
=> HTTP Reporter default batch size now inherited

sampler_remote.go, sampler_remote_options.go
- Fixes #577
- Use an `http.Client` with response timeout set to `10s` instead of the default of 0.
=> HTTPSamplingStrategyFetcher: Use http client with 10 second timeout

CHANGELOG.md, constants.go
- Releasing 2.28.0 to catch #578
=> Preparing for release 2.28.0

Makefile, thrift/README.md, thrift/logger.go
=> Remove dependency on "testing" in "thrift"

Makefile, scripts/gen-thrift.sh
Signed-off-by: Aaron Jheng <wentworth@outlook.com>
- make thrift is not working on Linux.
- Create a script for thrift compilation.
=> Move thrift compilation to a script
